### ISSUE TITLE
Add special characters

### ISSUE THREAD

**Issue by dereknguyen269** [dereknguyen269/ruby_letters#1]
Add special characters such as: 
 - **!**
-  **_**
..

**Comment by athyk** [comment]
I'd like to try this one!

**Comment by zilehuda** [comment]
work on it

**Comment by dereknguyen269** [comment]
Thanks @athyk @zilehuda  🙇

**Comment by dereknguyen269** [comment]
Some characters still missing. So, guys can adding them 😸

**Comment by zilehuda** [comment]
@dereknguyen269 is this thread closed ?

**Comment by dereknguyen269** [comment]
@zilehuda  some characters still not exists. You can PR. Thanks
